### Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score

In [3]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype=np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=np.float64)

In [4]:
X

array([[1.00e+00, 1.00e+00, 5.00e+02, 1.00e+00],
       [1.00e+00, 1.00e+00, 7.00e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 7.50e+02, 2.00e+00],
       [1.00e+00, 5.00e+00, 6.00e+02, 1.00e+00],
       [1.00e+00, 3.00e+00, 1.45e+03, 2.00e+00],
       [1.00e+00, 0.00e+00, 8.00e+02, 1.00e+00],
       [1.00e+00, 5.00e+00, 1.50e+03, 3.00e+00],
       [1.00e+00, 1.00e+01, 2.00e+03, 3.00e+00],
       [1.00e+00, 1.00e+00, 4.50e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 1.00e+03, 2.00e+00]])

In [5]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

In [6]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [7]:
X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])

In [8]:
X_st

array([[ 1.        ,  1.        , -0.97958969,  1.        ],
       [ 1.        ,  1.        , -0.56713087,  1.        ],
       [ 1.        ,  2.        , -0.46401617,  2.        ],
       [ 1.        ,  5.        , -0.77336028,  1.        ],
       [ 1.        ,  3.        ,  0.97958969,  2.        ],
       [ 1.        ,  0.        , -0.36090146,  1.        ],
       [ 1.        ,  5.        ,  1.08270439,  3.        ],
       [ 1.        , 10.        ,  2.11385144,  3.        ],
       [ 1.        ,  1.        , -1.08270439,  1.        ],
       [ 1.        ,  2.        ,  0.05155735,  2.        ]])

In [14]:
def calc_logloss(y, y_pred):
    y_pred_mod=np.where(y_pred==1, y_pred-1e-09, np.where(y_pred==0, y_pred+1e-09, y_pred))
    err = - np.mean(y * np.log(y_pred_mod) + (1.0 - y) * np.log(1.0 - y_pred_mod))
    return err

In [10]:
y1 = np.array([1, 0])
y_pred1 = np.array([0, 1])
calc_logloss_mod(y1, y_pred1)

20.723265851087376

### Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [11]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [12]:
def eval_model(X_st, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X_st.shape[1])
    n = X_st.shape[0]
    
    for i in range(iterations):
        z = np.dot(X_st, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X_st.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [15]:
W = eval_model(X_st, y, iterations=2000, eta=5.2)

0 [-1.47609763 -7.68281945  0.50531036 -1.42093074] 1.1785958344356262
200 [-24.55639078  -5.26645364  -4.21089798  24.36747991] 0.3382880398305177
400 [-31.09656747  -3.23266717  -8.2770825   25.72329935] 0.12129434171580529
600 [-33.46679836  -3.36700688  -9.00659354  27.59377365] 0.11536644326618795
800 [-34.95158211  -3.51739748  -9.41452937  28.81263251] 0.11176544909148309
1000 [-36.3415778   -3.65927807  -9.80837711  29.86926393] 0.10818031066505167
1200 [-37.62144683  -3.77291347 -10.16947476  30.89776884] 0.10544835561878596
1400 [-38.83284066  -3.8798663  -10.51149934  31.86974307] 0.10300389779116445
1600 [-39.98496672  -3.98098095 -10.83713776  32.79259581] 0.10079562364579328
1800 [-41.08530207  -4.07694026 -11.14853537  33.67244236] 0.09878399461509804


### Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1. На вход подаётся W, который уже посчитан функцией eval_model, и X, на выходе — массив y_pred_proba.

In [16]:
W

array([-42.13485652,  -4.16786447, -11.44599134,  34.51021508])

In [17]:
def calc_pred_proba(W, X): 
    pred_proba = sigmoid(np.dot(X, W))
    return pred_proba

In [18]:
calc_pred_proba1 = calc_pred_proba(W, X_st)
calc_pred_proba1.round(2)

array([0.36, 0.  , 1.  , 0.  , 0.96, 0.03, 1.  , 0.01, 0.65, 1.  ])

### Создайте функцию calc_pred, возвращающую предсказанный класс. На вход подаётся W, который уже посчитан функцией eval_model, и X, на выходе — массив y_pred.

In [39]:
def calc_pred(W, X, lim=0.7):    # lim -  порог, при превышении которого, объект будет относиться к классу 1
    pred_proba = sigmoid(np.dot(X, W))
    pred=np.zeros_like(pred_proba)
    for idx, prob in enumerate(pred_proba):
        if prob>lim:
            pred[idx]=1
    return pred

In [40]:
y_pred=calc_pred(W, X_st)
y_pred

array([0., 0., 1., 0., 1., 0., 1., 0., 0., 1.])

### Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [41]:
def manual_accuracy(real, pred):
    all_r = len(real)
    trues=0
    for i in range(all_r):
        trues+=int(real[i]==pred[i])
    return trues/all_r

In [42]:
manual_accuracy(y, y_pred), accuracy_score(y,y_pred)  #ручной рассчёт и проверка

(0.9, 0.9)

In [60]:
def manual_confusion_matrix(real, pred):
    n_classes=len(np.unique(real))
    all_res=len(real)
    conf_matr=np.zeros((n_classes,n_classes), dtype='int')
    for i in range(all_res):
        conf_matr[int(real[i])][int(pred[i])] += 1
    return conf_matr

In [61]:
manual_confusion_matrix(y, y_pred), confusion_matrix(y,y_pred)

(array([[5, 0],
        [1, 4]]),
 array([[5, 0],
        [1, 4]], dtype=int64))

In [62]:
def manual_precision(real, pred):
    tn, fp, fn, tp = manual_confusion_matrix(real, pred).ravel()
    return tp/(tp+fp)

In [63]:
manual_precision(y,y_pred), precision_score(y,y_pred)

(1.0, 1.0)

In [66]:
def manual_recall(real, pred):
    tn, fp, fn, tp = manual_confusion_matrix(real, pred).ravel()
    return tp/(tp+fn)

In [68]:
manual_recall(y,y_pred), recall_score(y,y_pred)

(0.8, 0.8)

In [69]:
def manual_f1(real, pred, beta=1):
    return (1+beta**2)*manual_precision(real, pred)*manual_recall(y,y_pred)/(beta**2*manual_precision(real, pred)+manual_recall(y,y_pred))

In [70]:
manual_f1(y,y_pred), f1_score(y,y_pred)

(0.888888888888889, 0.888888888888889)

### Могла ли модель переобучиться? Почему?

##### Модель логистической регрессии имеет склонность к переобучению по причине исспользования сигмоидной функции для получения вероятности предсказания линейной модели. Для предотвращения переобучения можно исспользовать L1 и L2 регуляризацию.