In [1]:
import torch

Создайте случайный FloatTensor размера 3x4x5

In [19]:
a = torch.randn(3, 4, 5).type(torch.FloatTensor)
a

tensor([[[-0.9823, -0.2516, -0.6579, -0.4889,  0.3443],
         [-0.7786, -1.7103,  1.2284, -0.6866,  1.5048],
         [ 0.1885, -0.8753, -1.4951, -0.7442, -0.6069],
         [-0.1465,  0.3308, -0.1332,  1.0816, -0.4156]],

        [[-0.9743, -0.7053, -0.3140, -1.1924,  1.3773],
         [-0.1620, -2.0341, -2.1237, -2.6193, -0.3678],
         [-0.2434,  0.1954, -0.0601, -0.2214, -1.3714],
         [-0.2179, -0.1153,  0.2337, -1.5162,  1.3192]],

        [[-1.8671,  0.8837,  1.2987,  1.2822, -1.2231],
         [-0.4781,  1.9960,  0.8487, -0.6024,  1.1464],
         [ 1.6116, -0.2955,  0.1930, -1.3616, -0.1624],
         [ 1.0530,  0.7587,  1.8468, -0.3202,  0.6408]]])

Выведите его форму (shape)

In [20]:
a.shape

torch.Size([3, 4, 5])

Приведите его к форме 6х10

In [21]:
a = a.reshape(6, 10)
a

tensor([[-0.9823, -0.2516, -0.6579, -0.4889,  0.3443, -0.7786, -1.7103,  1.2284,
         -0.6866,  1.5048],
        [ 0.1885, -0.8753, -1.4951, -0.7442, -0.6069, -0.1465,  0.3308, -0.1332,
          1.0816, -0.4156],
        [-0.9743, -0.7053, -0.3140, -1.1924,  1.3773, -0.1620, -2.0341, -2.1237,
         -2.6193, -0.3678],
        [-0.2434,  0.1954, -0.0601, -0.2214, -1.3714, -0.2179, -0.1153,  0.2337,
         -1.5162,  1.3192],
        [-1.8671,  0.8837,  1.2987,  1.2822, -1.2231, -0.4781,  1.9960,  0.8487,
         -0.6024,  1.1464],
        [ 1.6116, -0.2955,  0.1930, -1.3616, -0.1624,  1.0530,  0.7587,  1.8468,
         -0.3202,  0.6408]])

Создайте случайный IntTensor размера 10

In [22]:
b = torch.randint(10, size=(10,)).type(torch.IntTensor)
b

tensor([8, 2, 7, 8, 0, 6, 2, 3, 4, 4], dtype=torch.int32)

Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [24]:
c = a.mul(b)
c

tensor([[ -7.8585,  -0.5031,  -4.6054,  -3.9114,   0.0000,  -4.6719,  -3.4206,
           3.6853,  -2.7465,   6.0192],
        [  1.5082,  -1.7506, -10.4657,  -5.9534,  -0.0000,  -0.8790,   0.6616,
          -0.3995,   4.3262,  -1.6623],
        [ -7.7943,  -1.4107,  -2.1980,  -9.5390,   0.0000,  -0.9721,  -4.0681,
          -6.3712, -10.4771,  -1.4713],
        [ -1.9468,   0.3909,  -0.4206,  -1.7712,  -0.0000,  -1.3071,  -0.2307,
           0.7012,  -6.0648,   5.2766],
        [-14.9365,   1.7675,   9.0909,  10.2575,  -0.0000,  -2.8688,   3.9920,
           2.5462,  -2.4096,   4.5858],
        [ 12.8925,  -0.5909,   1.3513, -10.8931,  -0.0000,   6.3178,   1.5174,
           5.5405,  -1.2808,   2.5633]])

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [25]:
c.matmul(c.T)

tensor([[ 189.3998,   38.9966,  124.2916,   81.8658,   77.8535,  -59.9768],
        [  38.9966,  173.1613,   28.3344,  -22.9665, -195.7318,   54.6221],
        [ 124.2916,   28.3344,  328.5855,   85.9632,  -15.0754,  -36.6830],
        [  81.8658,  -22.9665,   85.9632,   74.1357,   51.2037,    9.9653],
        [  77.8535, -195.7318,  -15.0754,   51.2037,  471.5670, -276.1832],
        [ -59.9768,   54.6221,  -36.6830,    9.9653, -276.1832,  368.1773]])

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [29]:
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x ** 3 + z - 75 * t
y.backward()

print(f'd(y)/d(x) = {x.grad.item()} d(y)/d(z) = {z.grad.item()} d(y)/d(t) = {t.grad.item()}')

d(y)/d(x) = 3.0 d(y)/d(z) = 1.0 d(y)/d(t) = -75.0


Создайте единичный тензор размера 5x6

In [30]:
torch.ones((5, 6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

Переведите его в формат numpy

In [31]:
torch.ones((5, 6)).numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)