1. Найдите посредством NumPy SVD для матрицы:

In [35]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [36]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(A)

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [37]:
U, D, V = np.linalg.svd(A)
print(U)
print(D)
print(V)

[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
[8.82 6.14 2.53]
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


In [38]:
# Транспонируем матрицу W
V = V.T

In [39]:
D_matrix = np.zeros_like(A, dtype=float)
D_matrix[np.diag_indices(min(A.shape))] = D
print(D_matrix)

[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [40]:
print(f'Матрица D:\n{D_matrix}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [41]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [42]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1.  0. -0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [43]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [44]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [46]:
# Проведем проверку
print(np.dot(np.dot(U, D_matrix), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найдите:

а) евклидову норму;

б) норму Фробениуса.

In [47]:
print(D)

[8.82 6.14 2.53]


In [49]:
A_norm_E = D[0]
print(A_norm_E)

8.824868854820444


In [50]:
A_norm_F = np.linalg.norm(A)
print(A_norm_F)

11.045361017187261
